# Every PR needs two approvals from Zalando employees.
approvals:
  groups:
    zalando:
      minimum: 2
      from:
        orgs:
          - zalando
commit:
  message:
    patterns: # commit message has to match any one of
      - ".+" # Any non-empty message

X-Zalando-Team: automata
